"use strict";
// Core barrel — pure TypeScript, zero imports of electron/DOM/node.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.rollLoot = exports.coinsForIndex = exports.COIN_ITEM = exports.mulberry32 = exports.typeOf = exports.SPECIES_TYPE = exports.SPECIES_SIZE = exports.SPECIES_IDS = exports.SPECIES_ATTACK_DELAY_MS = exports.attackDelayOf = exports.sizeOf = exports.monsterForIndex = exports.isSpeciesId = exports.isBoss = exports.displayNameOf = exports.RARE_SPECIES_IDS = exports.COMMON_SPECIES_IDS = exports.BOSS_EVERY = exports.upgradeSave = exports.serializeSave = exports.parseSave = exports.DEFAULT_SAVE = exports.SimulatedInputDriver = exports.createFallbackGate = exports.tickMonster = exports.tickHero = exports.monsterKilled = exports.monsterHit = exports.MONSTER_SPAWNING_MS = exports.MONSTER_HIT_MS = exports.MONSTER_DYING_MS = exports.heroInput = exports.HERO_ATTACK_MS = exports.createMonsterAnim = exports.createHeroAnim = exports.RELEASES_PER_SOUL = exports.eligibleMonsterIds = exports.createEngine = exports.xpToNext = exports.xpReward = exports.monsterMaxHp = exports.fieldMonsterMaxHp = exports.damageForLevel = exports.CRIT_MULT = exports.CRIT_CHANCE = exports.suffix = exports.ratio = exports.format = exports.bigField = exports.CORE_VERSION = void 0;
exports.TRINKET_TABLE = exports.TRINKET_CHANCE = void 0;
exports.CORE_VERSION = '0.1.0';
var bignum_js_1 = require("./bignum.js");
Object.defineProperty(exports, "bigField", { enumerable: true, get: function () { return bignum_js_1.bigField; } });
Object.defineProperty(exports, "format", { enumerable: true, get: function () { return bignum_js_1.format; } });
Object.defineProperty(exports, "ratio", { enumerable: true, get: function () { return bignum_js_1.ratio; } });
Object.defineProperty(exports, "suffix", { enumerable: true, get: function () { return bignum_js_1.suffix; } });
var formulas_js_1 = require("./formulas.js");
Object.defineProperty(exports, "CRIT_CHANCE", { enumerable: true, get: function () { return formulas_js_1.CRIT_CHANCE; } });
Object.defineProperty(exports, "CRIT_MULT", { enumerable: true, get: function () { return formulas_js_1.CRIT_MULT; } });
Object.defineProperty(exports, "damageForLevel", { enumerable: true, get: function () { return formulas_js_1.damageForLevel; } });
Object.defineProperty(exports, "fieldMonsterMaxHp", { enumerable: true, get: function () { return formulas_js_1.fieldMonsterMaxHp; } });
Object.defineProperty(exports, "monsterMaxHp", { enumerable: true, get: function () { return formulas_js_1.monsterMaxHp; } });
Object.defineProperty(exports, "xpReward", { enumerable: true, get: function () { return formulas_js_1.xpReward; } });
Object.defineProperty(exports, "xpToNext", { enumerable: true, get: function () { return formulas_js_1.xpToNext; } });
__exportStar(require("./battle.js"), exports);
__exportStar(require("./hero.js"), exports);
__exportStar(require("./progress.js"), exports);
__exportStar(require("./economy.js"), exports);
__exportStar(require("./gold.js"), exports);
__exportStar(require("./equipment.js"), exports);
__exportStar(require("./discovery.js"), exports);
__exportStar(require("./progression.js"), exports);
__exportStar(require("./collection.js"), exports);
__exportStar(require("./fever.js"), exports);
__exportStar(require("./types-chart.js"), exports);
var engine_js_1 = require("./engine.js");
Object.defineProperty(exports, "createEngine", { enumerable: true, get: function () { return engine_js_1.createEngine; } });
Object.defineProperty(exports, "eligibleMonsterIds", { enumerable: true, get: function () { return engine_js_1.eligibleMonsterIds; } });
Object.defineProperty(exports, "RELEASES_PER_SOUL", { enumerable: true, get: function () { return engine_js_1.RELEASES_PER_SOUL; } });
var fsm_js_1 = require("./fsm.js");
Object.defineProperty(exports, "createHeroAnim", { enumerable: true, get: function () { return fsm_js_1.createHeroAnim; } });
Object.defineProperty(exports, "createMonsterAnim", { enumerable: true, get: function () { return fsm_js_1.createMonsterAnim; } });
Object.defineProperty(exports, "HERO_ATTACK_MS", { enumerable: true, get: function () { return fsm_js_1.HERO_ATTACK_MS; } });
Object.defineProperty(exports, "heroInput", { enumerable: true, get: function () { return fsm_js_1.heroInput; } });
Object.defineProperty(exports, "MONSTER_DYING_MS", { enumerable: true, get: function () { return fsm_js_1.MONSTER_DYING_MS; } });
Object.defineProperty(exports, "MONSTER_HIT_MS", { enumerable: true, get: function () { return fsm_js_1.MONSTER_HIT_MS; } });
Object.defineProperty(exports, "MONSTER_SPAWNING_MS", { enumerable: true, get: function () { return fsm_js_1.MONSTER_SPAWNING_MS; } });
Object.defineProperty(exports, "monsterHit", { enumerable: true, get: function () { return fsm_js_1.monsterHit; } });
Object.defineProperty(exports, "monsterKilled", { enumerable: true, get: function () { return fsm_js_1.monsterKilled; } });
Object.defineProperty(exports, "tickHero", { enumerable: true, get: function () { return fsm_js_1.tickHero; } });
Object.defineProperty(exports, "tickMonster", { enumerable: true, get: function () { return fsm_js_1.tickMonster; } });
var input_js_1 = require("./input.js");
Object.defineProperty(exports, "createFallbackGate", { enumerable: true, get: function () { return input_js_1.createFallbackGate; } });
Object.defineProperty(exports, "SimulatedInputDriver", { enumerable: true, get: function () { return input_js_1.SimulatedInputDriver; } });
var save_js_1 = require("./save.js");
Object.defineProperty(exports, "DEFAULT_SAVE", { enumerable: true, get: function () { return save_js_1.DEFAULT_SAVE; } });
Object.defineProperty(exports, "parseSave", { enumerable: true, get: function () { return save_js_1.parseSave; } });
Object.defineProperty(exports, "serializeSave", { enumerable: true, get: function () { return save_js_1.serializeSave; } });
Object.defineProperty(exports, "upgradeSave", { enumerable: true, get: function () { return save_js_1.upgradeSave; } });
var monsters_js_1 = require("./monsters.js");
Object.defineProperty(exports, "BOSS_EVERY", { enumerable: true, get: function () { return monsters_js_1.BOSS_EVERY; } });
Object.defineProperty(exports, "COMMON_SPECIES_IDS", { enumerable: true, get: function () { return monsters_js_1.COMMON_SPECIES_IDS; } });
Object.defineProperty(exports, "RARE_SPECIES_IDS", { enumerable: true, get: function () { return monsters_js_1.RARE_SPECIES_IDS; } });
Object.defineProperty(exports, "displayNameOf", { enumerable: true, get: function () { return monsters_js_1.displayNameOf; } });
Object.defineProperty(exports, "isBoss", { enumerable: true, get: function () { return monsters_js_1.isBoss; } });
Object.defineProperty(exports, "isSpeciesId", { enumerable: true, get: function () { return monsters_js_1.isSpeciesId; } });
Object.defineProperty(exports, "monsterForIndex", { enumerable: true, get: function () { return monsters_js_1.monsterForIndex; } });
Object.defineProperty(exports, "sizeOf", { enumerable: true, get: function () { return monsters_js_1.sizeOf; } });
Object.defineProperty(exports, "attackDelayOf", { enumerable: true, get: function () { return monsters_js_1.attackDelayOf; } });
Object.defineProperty(exports, "SPECIES_ATTACK_DELAY_MS", { enumerable: true, get: function () { return monsters_js_1.SPECIES_ATTACK_DELAY_MS; } });
Object.defineProperty(exports, "SPECIES_IDS", { enumerable: true, get: function () { return monsters_js_1.SPECIES_IDS; } });
Object.defineProperty(exports, "SPECIES_SIZE", { enumerable: true, get: function () { return monsters_js_1.SPECIES_SIZE; } });
Object.defineProperty(exports, "SPECIES_TYPE", { enumerable: true, get: function () { return monsters_js_1.SPECIES_TYPE; } });
Object.defineProperty(exports, "typeOf", { enumerable: true, get: function () { return monsters_js_1.typeOf; } });
var rng_js_1 = require("./rng.js");
Object.defineProperty(exports, "mulberry32", { enumerable: true, get: function () { return rng_js_1.mulberry32; } });
var loot_js_1 = require("./loot.js");
Object.defineProperty(exports, "COIN_ITEM", { enumerable: true, get: function () { return loot_js_1.COIN_ITEM; } });
Object.defineProperty(exports, "coinsForIndex", { enumerable: true, get: function () { return loot_js_1.coinsForIndex; } });
Object.defineProperty(exports, "rollLoot", { enumerable: true, get: function () { return loot_js_1.rollLoot; } });
Object.defineProperty(exports, "TRINKET_CHANCE", { enumerable: true, get: function () { return loot_js_1.TRINKET_CHANCE; } });
Object.defineProperty(exports, "TRINKET_TABLE", { enumerable: true, get: function () { return loot_js_1.TRINKET_TABLE; } });
