"use strict";
// Sprites barrel — one import surface for the renderer (T13+). Importing it
// side-effect-registers ALL art modules into the sprite registry.
Object.defineProperty(exports, "__esModule", { value: true });
exports.fontSprite = exports.FONT_W = exports.FONT_H = exports.FONT_ADVANCE = exports.drawText = exports.drawFeverAura = exports.TYPE_COLORS = exports.TYPE_BADGE_DY = exports.partySlots = exports.PARTY_X = exports.PARTY_STEP_Y = exports.PARTY_STEP_X = exports.drawTypeBadge = exports.drawPartyBadges = exports.drawParty = exports.drawFootBadge = exports.drawCompanion = exports.drawBoss = exports.BOSS_HP_BAR_Y = exports.itemSprites = exports.ITEM_SPRITE_IDS = exports.monsterSprites = exports.EQUIPPED_HERO_PADDING = exports.HERO_HANDS = exports.heroEquipmentPose = exports.heroBodyLayers = exports.equippedHeroSprite = exports.drawEquippedHero = exports.ITEM_RARITY_COLORS = exports.equipmentColor = exports.equipmentIcon = exports.drawEquipmentIcon = exports.heroFormSprite = exports.HERO_FORM_IDS = exports.drawHeroForm = exports.heroSlash = exports.heroIdle = exports.heroAttack = exports.HERO_RIVAL_PALETTE = exports.tintPalette = exports.TIER_HUE_STEP = exports.shiftHue = exports.paletteForTier = exports.hslToHex = exports.hexToHsl = exports.COLORS = exports.TRANSPARENT = exports.registerSprites = exports.drawSprite = exports.allSprites = void 0;
exports.textWidth = exports.glyphIndex = exports.GLYPH_CHARS = void 0;
var sprite_js_1 = require("./sprite.js");
Object.defineProperty(exports, "allSprites", { enumerable: true, get: function () { return sprite_js_1.allSprites; } });
Object.defineProperty(exports, "drawSprite", { enumerable: true, get: function () { return sprite_js_1.drawSprite; } });
Object.defineProperty(exports, "registerSprites", { enumerable: true, get: function () { return sprite_js_1.registerSprites; } });
Object.defineProperty(exports, "TRANSPARENT", { enumerable: true, get: function () { return sprite_js_1.TRANSPARENT; } });
var palette_js_1 = require("./palette.js");
Object.defineProperty(exports, "COLORS", { enumerable: true, get: function () { return palette_js_1.COLORS; } });
Object.defineProperty(exports, "hexToHsl", { enumerable: true, get: function () { return palette_js_1.hexToHsl; } });
Object.defineProperty(exports, "hslToHex", { enumerable: true, get: function () { return palette_js_1.hslToHex; } });
Object.defineProperty(exports, "paletteForTier", { enumerable: true, get: function () { return palette_js_1.paletteForTier; } });
Object.defineProperty(exports, "shiftHue", { enumerable: true, get: function () { return palette_js_1.shiftHue; } });
Object.defineProperty(exports, "TIER_HUE_STEP", { enumerable: true, get: function () { return palette_js_1.TIER_HUE_STEP; } });
Object.defineProperty(exports, "tintPalette", { enumerable: true, get: function () { return palette_js_1.tintPalette; } });
var hero_js_1 = require("./hero.js");
Object.defineProperty(exports, "HERO_RIVAL_PALETTE", { enumerable: true, get: function () { return hero_js_1.HERO_RIVAL_PALETTE; } });
Object.defineProperty(exports, "heroAttack", { enumerable: true, get: function () { return hero_js_1.heroAttack; } });
Object.defineProperty(exports, "heroIdle", { enumerable: true, get: function () { return hero_js_1.heroIdle; } });
Object.defineProperty(exports, "heroSlash", { enumerable: true, get: function () { return hero_js_1.heroSlash; } });
var heroForms_js_1 = require("./heroForms.js");
Object.defineProperty(exports, "drawHeroForm", { enumerable: true, get: function () { return heroForms_js_1.drawHeroForm; } });
Object.defineProperty(exports, "HERO_FORM_IDS", { enumerable: true, get: function () { return heroForms_js_1.HERO_FORM_IDS; } });
Object.defineProperty(exports, "heroFormSprite", { enumerable: true, get: function () { return heroForms_js_1.heroFormSprite; } });
var equipment_js_1 = require("./equipment.js");
Object.defineProperty(exports, "drawEquipmentIcon", { enumerable: true, get: function () { return equipment_js_1.drawEquipmentIcon; } });
Object.defineProperty(exports, "equipmentIcon", { enumerable: true, get: function () { return equipment_js_1.equipmentIcon; } });
Object.defineProperty(exports, "equipmentColor", { enumerable: true, get: function () { return equipment_js_1.equipmentColor; } });
Object.defineProperty(exports, "ITEM_RARITY_COLORS", { enumerable: true, get: function () { return equipment_js_1.ITEM_RARITY_COLORS; } });
var equippedHero_js_1 = require("./equippedHero.js");
Object.defineProperty(exports, "drawEquippedHero", { enumerable: true, get: function () { return equippedHero_js_1.drawEquippedHero; } });
Object.defineProperty(exports, "equippedHeroSprite", { enumerable: true, get: function () { return equippedHero_js_1.equippedHeroSprite; } });
Object.defineProperty(exports, "heroBodyLayers", { enumerable: true, get: function () { return equippedHero_js_1.heroBodyLayers; } });
Object.defineProperty(exports, "heroEquipmentPose", { enumerable: true, get: function () { return equippedHero_js_1.heroEquipmentPose; } });
Object.defineProperty(exports, "HERO_HANDS", { enumerable: true, get: function () { return equippedHero_js_1.HERO_HANDS; } });
Object.defineProperty(exports, "EQUIPPED_HERO_PADDING", { enumerable: true, get: function () { return equippedHero_js_1.EQUIPPED_HERO_PADDING; } });
var monsters_js_1 = require("./monsters.js");
Object.defineProperty(exports, "monsterSprites", { enumerable: true, get: function () { return monsters_js_1.monsterSprites; } });
var items_js_1 = require("./items.js");
Object.defineProperty(exports, "ITEM_SPRITE_IDS", { enumerable: true, get: function () { return items_js_1.ITEM_SPRITE_IDS; } });
Object.defineProperty(exports, "itemSprites", { enumerable: true, get: function () { return items_js_1.itemSprites; } });
var boss_js_1 = require("./boss.js");
Object.defineProperty(exports, "BOSS_HP_BAR_Y", { enumerable: true, get: function () { return boss_js_1.BOSS_HP_BAR_Y; } });
Object.defineProperty(exports, "drawBoss", { enumerable: true, get: function () { return boss_js_1.drawBoss; } });
var companion_js_1 = require("./companion.js");
Object.defineProperty(exports, "drawCompanion", { enumerable: true, get: function () { return companion_js_1.drawCompanion; } });
var party_js_1 = require("./party.js");
Object.defineProperty(exports, "drawFootBadge", { enumerable: true, get: function () { return party_js_1.drawFootBadge; } });
Object.defineProperty(exports, "drawParty", { enumerable: true, get: function () { return party_js_1.drawParty; } });
Object.defineProperty(exports, "drawPartyBadges", { enumerable: true, get: function () { return party_js_1.drawPartyBadges; } });
Object.defineProperty(exports, "drawTypeBadge", { enumerable: true, get: function () { return party_js_1.drawTypeBadge; } });
Object.defineProperty(exports, "PARTY_STEP_X", { enumerable: true, get: function () { return party_js_1.PARTY_STEP_X; } });
Object.defineProperty(exports, "PARTY_STEP_Y", { enumerable: true, get: function () { return party_js_1.PARTY_STEP_Y; } });
Object.defineProperty(exports, "PARTY_X", { enumerable: true, get: function () { return party_js_1.PARTY_X; } });
Object.defineProperty(exports, "partySlots", { enumerable: true, get: function () { return party_js_1.partySlots; } });
Object.defineProperty(exports, "TYPE_BADGE_DY", { enumerable: true, get: function () { return party_js_1.TYPE_BADGE_DY; } });
Object.defineProperty(exports, "TYPE_COLORS", { enumerable: true, get: function () { return party_js_1.TYPE_COLORS; } });
var aura_js_1 = require("./aura.js");
Object.defineProperty(exports, "drawFeverAura", { enumerable: true, get: function () { return aura_js_1.drawFeverAura; } });
var font_js_1 = require("./font.js");
Object.defineProperty(exports, "drawText", { enumerable: true, get: function () { return font_js_1.drawText; } });
Object.defineProperty(exports, "FONT_ADVANCE", { enumerable: true, get: function () { return font_js_1.FONT_ADVANCE; } });
Object.defineProperty(exports, "FONT_H", { enumerable: true, get: function () { return font_js_1.FONT_H; } });
Object.defineProperty(exports, "FONT_W", { enumerable: true, get: function () { return font_js_1.FONT_W; } });
Object.defineProperty(exports, "fontSprite", { enumerable: true, get: function () { return font_js_1.fontSprite; } });
Object.defineProperty(exports, "GLYPH_CHARS", { enumerable: true, get: function () { return font_js_1.GLYPH_CHARS; } });
Object.defineProperty(exports, "glyphIndex", { enumerable: true, get: function () { return font_js_1.glyphIndex; } });
Object.defineProperty(exports, "textWidth", { enumerable: true, get: function () { return font_js_1.textWidth; } });
