// Original rare creatures, facing left. Each matrix authors a different body
// and identifying feature; animation breathes down and recoils right. Native
// canvas bands preserve the existing hidden-size contract and uniform scale.
import { RARE_MONSTERS } from '../../../core/discovery.js';
import { COLORS } from '../palette.js';
import type { Sprite } from '../sprite.js';
import type { SpeciesSprites } from '../monsters.js';

type RareId = (typeof RARE_MONSTERS)[number]['id'];
const drawings: Record<RareId, string> = {
  // Sun comb, hooked beak, plump bird and two separate planted claws.
  dawnfinch: `....e.e.......
...eaeae......
..eaaaae......
.eewbbbbee....
eabebbbbbe....
.eebbbassbe...
..ebbaaasse...
...esssse....
...eae.eae...
...eee.eee...`,
  // Brick dome, glowing furnace entrance and three pairs of hooked legs.
  kilnbeetle: `.......eee......
....eeebbbee....
...ebbbebbbee...
..ebebbbebbbee..
..ebbbebbebbbee.
.eebbbbaaabbbe..
ebwebaaeaabbbe..
ebebbaeaeaasse..
.eebbaaassssse..
.e.eesssssee.e..
eae..e..e..eae..
ee..eae.eae.ee..
....eee.eee.....`,
  // Three-pronged connected crown, heavy left-facing jaw and wing.
  crownwyrm: `.....e..e..e.......
....eaeaeaee.......
....eaaaaae....e...
...eebbbbee...eae..
..ebbbbbbbe.eebae..
.ebbweebbbbeababe..
ebbbewbbbbeabbabe..
ebbbbbbbbeabbabe...
.eewasssebbbbee....
..esssssebbbbee....
...eeeeebaabbbbe...
.......ebaaabbbbe..
......ebbaaabssbe..
.....ebbseeesssbe..
.....eae....eae...
.....eee....eee...`,
  // Long pinching ears, forward cheeks and a blocky coal tail.
  cinderhare: `....ee..ee....
...ebe.ebbe...
...ebe.ebbe...
..eebeeebbe...
.ebbwebbbbee..
ebbbewbbbbbbe.
.ebbbbbbaasee.
..essssaaaebe.
.eebseessseee.
.eeee.eeee....`,
  // One long shield wing and short wounded wing, hooked phoenix beak.
  duelphoenix: `....ee.........
...eaae........
..eabbbe.......
.ewebbbe..ee...
eabebbbe.eaae..
.eebbbbeeaabe..
...ebbaaababe..
..eebaaababbe..
.eabbaaabssbe..
eabasssssssbe..
.eeeesssssee...
.....e..e......
....eae.eae....
....eee.eee....`,
  // Forward curling horns, broad quadruped back and round glowing furnace.
  furnaceox: `...ee....ee.........
..eabe..eabe........
..eabeeeeabe........
...eebbbbee.........
..ebbweebbbeeee.....
.ebbbewbbbbbbbbe....
ebbbbbbbbbbbbbbbe...
ebbbbbbaaabbbbbbbe..
.eessbaeaeaabbbbse..
..eebbaeaeaabbbse...
...ebbaaaaassssse...
...ebssssssssssse...
...ebsseeeesssse....
..ebsse....essbe....
..eabe.....eabe.....
..eeee.....eeee.....`,
  // Three-branched exposed gills and wide salamander smile.
  mistaxolotl: `..e....e......
.eae..eae.....
eae.ee.eae....
.eebbbbbee....
ebbwebbbbbe...
ebbbebbbbbbee.
.eewawbbbbbse.
..eebbbssssse.
.eabeeessabe..
.eeee...eeee..`,
  // A large pearl held aloft by a single long claw; squat crab body below.
  pearlcrab: `..........eee...
.........eawwe..
.........eawwe..
..........eae...
..ee......ebe...
.eabe..ee.ebe...
..ebeeeeebe.....
.eebbweebbee....
eabbbeebbbabe...
.eebbbbbbbee....
.e.eesssee.e...
eae..e.e..eae..
eee.eaeae.eee..
....eeeee......`,
  // Wave-shaped forehead, enormous rounded whale torso and tiny forked tail.
  tideleviathan: `.....eee............
....eaaae...........
...eaeeabee.........
..eabbbbbbbe........
.ebbbbbbbbbbe.......
ebbweebbbbbbbee.....
ebbbewbbbbbbbbbe....
ebbbbbbbbbbbbbbee.e.
ebbbbbbaaaaaabbbebae
.ebbbbaaaaaaabbbbbae
..ebbbaaaaaabbbebae.
...ebbaaaasssse.e...
....ebssssssse......
.....eeesssee.......
........eaae........
........eeee........`,
  // Three tall ice plates, low long body, pointed snout and short feet.
  frostnewt: `.....e.e.e....
....eaeaeae...
....eaaeaae...
..eebbbbbe....
.ewebbbbbbe...
eabebbbbbbbee.
.eebbbbbbssbe.
...ebssssssse.
..eabe.eabe...
..eeee.eeee...`,
  // Square mirror bell, two reflected eyes and five unequal hanging ribbons.
  mirrorjelly: `...eeeeeeee....
..etaaaaaate...
.etawwwwwaate..
.etawebewaate..
.etawwwwwaate..
.etaawwwaaate..
..etaaaaaate...
...esssssse....
..eseeseesee...
..ese.eese.se..
..e.e..ese.ee..
....ee.e.e.....
.......ee......`,
  // Pointed squid hood; the two long outer tentacles terminate in anchors.
  anchornaut: `........e...........
.......ebe..........
......ebbbee........
.....ebbbbbee.......
....ebbbbbbbe.......
...ebbbbbbbbbe......
..ebbweebbbbbbe.....
..ebbbewbbbbbse.....
...ebbbbbbbbse......
....ebsssssee.......
...ebebesebbe.......
..ebe.ese.ebbe......
..ebe.ese..ebe......
.eabe.e.e..ebae.....
eaabe.......ebaae...
.eee.........eee....`,
  // Backward fan, alert antennae and oversized bent grasshopper legs.
  sunskipper: `...e....e.....
...ee..ee.e...
..ebbbee.eae..
.ebwebbeeaae..
ebbebbbbaaae..
.eebbbbasse...
..eebbssebe...
.eabe.ee.ebe..
eabe.....eae..
eeee.....eee..`,
  // Broad ear tufts and a folded-envelope breast with two planted toes.
  courierowl: `.ee.......ee...
.ebe.....ebe...
.ebeeeeeeebe...
..ebbbbbbbe....
.eebweewbbee...
ebbbebeebbbbe..
ebbbaaaaabbbe..
.ebbaaeaaabbe..
.ebbaaeeaabbe..
..ebaaaaabbe...
...esssssse....
....e...e......
...eae.eae.....
...eee.eee.....`,
  // Jagged lightning wings are part of the flat manta body, with a long tail.
  stormmanta: `..e.............e...
..ebe.........ebe...
...ebee.....eebbe...
..eabbbbeeebbbbae...
.eabbbbbbbbbbbbae...
eabbbbweebbbbbbbbae.
.eabbbbewbbbbbbbae..
..eabbbbbbbbbbbae...
.eabbbbaaaabbbbae...
..eabbaaasssbbae....
...eeassssssee......
.....eesssee........
........ese.........
.........ese........
.........ese........
..........ee........`,
  // Stretched stoat torso and a forked ribbon tail tied at its base.
  ribbonstoat: `...ee.........
..ebbe....e.e.
..ebbe...eaeae
.eebbbee..eae.
ebbwebbbbeebe.
ebbbewbbbbbbe.
.eebbbbbsssse.
...ebssssse...
..eabe.eabe...
..eeee.eeee...`,
  // Short crested hunting kite with one unfolded wing and armored shins.
  arenakite: `....ee..........
...eaae.........
..eabbbe........
.ewebbbe........
eabebbbe....ee..
.eebbbbbee.eabe.
...ebaaaabeabbe.
..ebbaaabbabbbe.
.ebbbassssbbe...
..eeesssssee....
.....ete.ete....
.....ete.ete....
....eaae.eaae...
....eeee.eeee...`,
  // Weather-vane antlers above a slender deer and tucked, curled tail.
  zephyrstag: `..eee.......eee....
..eae.......eae....
...ebe.....ebe.....
...ebee.eeeebe.....
....ebbebbbbe......
...ebbweebbbe......
..ebbbbewbbbe......
..ebbbbbbbbe.......
...eebbbbbbeeee.e..
.....ebbbbbbbbbeae.
.....ebaaaaabbbbe..
.....ebassssssse...
.....ebsseessse....
.....ebse..esbe....
....eabe...eabe....
....eeee...eeee....`,
  // Diagonal overlapping stone scales and a long narrow armored snout.
  duskarmadillo: `......eee.....
....eebbbee...
...ebbeebbbee.
..ebbeebbebbe.
.eebbebbeebbe.
ebbwebbebbebe.
ebbbebbebbse..
.eebssssssse..
..eabe.eabe...
..eeee.eeee...`,
  // Soft moss mound on a low badger; light mask points left.
  mossbadger: `.......ee.......
.....eeaaee.....
....eaaaeaee....
...eaaaaaaabe...
..eebbbbbbbbbe..
.ebbweebbbbbbe..
ebawbewbbbbbbe.
ebaaabbbbbbbse..
.eebbbasssssse..
...ebassssse....
...ebsseesse....
..eabe..eabe....
..eeee..eeee....`,
  // Single hexagonal crystal set into a broad turtle shell.
  crystaltortoise: `.........eee........
........eatwe.......
.......eaatwwe......
.......eaatwwe......
........eatwe.......
......eeeeeeeee.....
.....ebbbabbbbbe....
....ebabbabbabbbe...
.eeeebbabbabbabbbe..
ebbwebbabbabbabbbe..
ebbbebbbbbbbbbbse...
.eebbbssssssssse....
...ebsseeeessse.....
...ebse....esbe.....
..eabe.....eabe.....
..eeee.....eeee.....`,
  // Coin-ring nose protrudes from a dark round mole with broad digging claws.
  coinmole: `.....eeee.....
....ebbbbe....
...ebbbbbbe...
.eebbweebbbe..
eaaebbebbbbbe.
eawebbbbbbbse.
eaaeabbbassse.
.eeeassssse...
..eawwe.eawe..
..eeeee.eeee..`,
  // Stone oath tablet between upright horns and a heavy shaggy bison neck.
  oathbison: `..e.......e....
.eae.....eae...
.eaeeeeeeaae...
..eatttttae....
..eatataaae....
...eebbbeee....
..ebbweebbbe...
.ebbbbewbbbbee.
ebbbbbbbbbbbse.
.eessbbbbssse..
..eebssssssse..
..ebsseessse...
.eabe..eabe....
.eeee..eeee....`,
  // Hollow stump face, branching arms and two thick walking root legs.
  rootcolossus: `......e...e.........
.....ebe.ebe........
...eeebeeebee.......
..ebbbbbbbbbbe......
..ebbweewbbbbbe.....
...ebbebebbbbse.....
.e.ebbbbawbbbse.e...
ebeebbbbaaabbbeebe..
ebbbbbbbbaabbbbbbse.
.eeeebbbbaabbbbeee..
....ebbbaabbbse.....
....ebbbabbbse......
...ebbbseeebbe......
..ebbbse..ebbbe.....
.ebabbse..ebbabe....
.eeeeee...eeeeee....`,
  // Round moth wings contain real transparent crescent cut-outs.
  moonmoth: `..ee.....ee...
.eaae...eaae..
eaa.e.e.eaae..
eaa..ebe.eae..
eaaaebwbeaae..
.eaaabebaaae..
..eaabbbaae...
..eaaebeaee...
...ee.e.ee....
......e.......`,
  // Ferret in a low crouch; brush-like tail spreads into three sharp bristles.
  inkferret: `...ee...........
..ebbe..........
..ebbe.....e.e..
.eebbbee..ebebe.
ebbwebbbbeebbbee
ebbbewbbbbbbbse.
.eebbbbbbbbssse.
...ebbbbbsssse..
...ebssssse.....
...ebsseese.....
..eabe.eabe.....
..eeee.eeee.....
...............`,
  // Rectangular gravestone antlers carved with pale runes, broad deer body.
  cryptcervid: `...eeee.....eeee....
...eaae.....eaae....
...eawe.....eawe....
...eaae.....eaae....
....ebe.....ebe.....
....ebeeeeeeebe.....
...ebbweebbbbbbe....
..ebbbbewbbbbbbe....
..ebbbbbbbbbbbee....
...eebbbbbbbbbbbe...
.....ebaaaaabbbse...
.....ebasssssssse...
.....ebsseeeessse...
.....ebse....esbe...
....eabe.....eabe...
....eeee.....eeee...`,
  // Half a smiling white mask extends past the imp's round head and ears.
  maskimp: `..e......e....
.ebe....ebe...
..ebeeeeebe...
.eaawwbbbbbe..
eaawewbbbbbse.
eaaawwbbbbse..
.eeaawbbbse...
...ebsssse....
..eabe.eabe...
..eeee.eeee...`,
  // Leafy laurel wreath, curved beak, short crow wing and forked tail.
  victoryraven: `...e.e.e.......
..eaeaeae......
..eaaaaae......
.eebbwbbe......
eabbebbbbe.....
.eebbbbbbee....
...ebaaabbbbe..
..ebaaaabbbbe..
.ebbaaaassbe...
..eessssse.....
...e.eessee....
..eae...eae....
..eee...eee....`,
  // Flattened floating body with a sharply cut star mouth and scalloped rim.
  starvoid: `....................
.......eeeeee.......
.....eebbbbbbee.....
...eebbbbbbbbbbee...
..ebbbbbabbbbbbbbe..
.ebbbbbaaaabbbbbbse.
ebbbaaaaaaaaaabbbbse
ebbbbaaa.aaabbbbbbse
.ebbbbbaaaabbbbbbse.
..ebbbabbbabbbbbse..
...ebbbbbbbbbbbse...
....eesssssssee.....
...eseeessseeese....
....ee..ee..ee......
....................
....................`,
};
const elementColors = {
  fire: [COLORS.red, COLORS.maroon, COLORS.orange],
  water: [COLORS.cyan, COLORS.navy, COLORS.blue],
  wind: [COLORS.green, COLORS.forest, COLORS.yellow],
  earth: [COLORS.brown, COLORS.slate, COLORS.green],
  dark: [COLORS.navy, COLORS.maroon, COLORS.steel],
} as const;
export const rareSprites = Object.fromEntries(RARE_MONSTERS.map((monster) => {
  const [w, h] = monster.size === 1 ? [15, 11] : monster.size === 2 ? [17, 14] : [20, 17];
  const [b, s, a] = elementColors[monster.type];
  const palette = { e: COLORS.void, b, s, a, w: COLORS.white, t: COLORS.steel };
  const rows = drawings[monster.id].split('\n');
  if (rows.length > h || rows.some(row => row.length > w)) throw new Error(`Rare art exceeds size band: ${monster.id}`);
  const frame = [...rows.map(row => row.padEnd(w, '.')), ...Array<string>(h - rows.length).fill('.'.repeat(w))];
  const breathe = ['.'.repeat(w), ...frame.slice(0, h - 1)];
  const recoil = frame.map((row, y) => y < 2 ? '.'.repeat(w) : '.' + row.slice(0, w - 1));
  const idle: Sprite = { w, h, palette, frames: [frame, breathe] };
  const hit: Sprite = { w, h, palette, frames: [recoil] };
  return [monster.id, { idle, hit }];
})) as Record<RareId, SpeciesSprites>;
