// Monster catalog: 105 species, 21 per element. The engine picks each spawn
// uniformly at random; catalog order is retained for legacy save restoration.
// tier = Math.floor(index / SPECIES_IDS.length) → renderer hue tint.
//
// Boss cadence depends on progress, independently of the selected species.
//
// The five tables below are GENERATED from the roster (user request 2026-09-08:
// "at least 100 monster kinds"); the art lives in src/renderer/sprites/species/.

import { monsterMaxHp } from './formulas.js';
import type { MonsterType } from './types-chart.js';
import type { MonsterDef } from './types.js';

/** Stable catalog order used by legacy saves. Never reorder. */
export const SPECIES_IDS = [
  'slime', 'bat', 'ghost', 'golem', 'dragon',
  'lumibel', 'kitekin', 'rictus', 'lichenwing', 'brimhide',
  'sopwit', 'nimbling', 'hexweaver', 'sumpfang', 'anvilclaw',
  'snipclaw', 'panewhirr', 'chainwraith', 'bramblebear', 'ashtusk',
  'vespril', 'fanjack', 'gravebloom', 'fellstump', 'forgehulk',
  'murkin', 'skitterel', 'cryptshell', 'quarryback', 'bristlehog',
  'foamcap', 'sporeplume', 'sorrowstilt', 'kabulk', 'matchling',
  'gulpwick', 'chimbrel', 'sicklehood', 'quagmaw', 'wickmoth',
  'brammel', 'lantessa', 'hollowstag', 'wickerhusk', 'emberwren',
  'conchguard', 'vaneknight', 'voidmaw', 'grumblode', 'sootcap',
  'bellbuoy', 'skreave', 'shroudlamp', 'chirrgrit', 'steamfin',
  'quintel', 'curlhart', 'gallowplate', 'gillstub', 'kindletoad',
  'pondstrider', 'gyrodillo', 'mournbell', 'cobbleroll', 'flarecrow',
  'slushmaw', 'cyclonarch', 'hooklure', 'flintwren', 'hearthmole',
  'kraulk', 'vellisk', 'quietus', 'moldwarp', 'scorchbriar',
  'reefknight', 'millox', 'unblink', 'spadeling', 'kilnshell',
  'grumbol', 'nubilan', 'glasshade', 'helmdelver', 'charspine',
  'vorrow', 'dartfinch', 'inknuckle', 'thornhare', 'pyrecairn',
  'rainheron', 'glidefin', 'veilcap', 'cairnlith', 'slagram',
  'clubprawn', 'whirlseed', 'waxwick', 'drusehog', 'coalscythe',
  'kelpwarden', 'velmoth', 'nightlynx', 'terrakin', 'cindercoil',
] as const;

export type SpeciesId = (typeof SPECIES_IDS)[number];

/** Fast membership test for runtime species ids (SPECIES_IDS is 105 long). */
const SPECIES_ID_SET: ReadonlySet<string> = new Set<string>(SPECIES_IDS);

/** True when `speciesId` is one of the catalog's species. */
export function isSpeciesId(speciesId: string): speciesId is SpeciesId {
  return SPECIES_ID_SET.has(speciesId);
}

/** Boss cadence (SPEC F31): every 8th monster — index 7, 15, 23 … */
export const BOSS_EVERY = 8;

/** Boss slots depend only on progress, not species. */
export const isBoss = (index: number): boolean =>
  index >= 0 && index % BOSS_EVERY === BOSS_EVERY - 1;

/** Boss rewards: 5x hp (bigint, F30), 5x xp and 5x coins (applied by the engine). */
export const BOSS_HP_MULT = 5n;
export const BOSS_XP_MULT = 5;
export const BOSS_COIN_MULT = 5;

/** Elemental type per species (GAME_DESIGN_V3 §1) — visible in HUD/menu badges. */
export const SPECIES_TYPE: Record<SpeciesId, MonsterType> = {
  slime: 'water',
  bat: 'wind',
  ghost: 'dark',
  golem: 'earth',
  dragon: 'fire',
  lumibel: 'water',
  kitekin: 'wind',
  rictus: 'dark',
  lichenwing: 'earth',
  brimhide: 'fire',
  sopwit: 'water',
  nimbling: 'wind',
  hexweaver: 'dark',
  sumpfang: 'earth',
  anvilclaw: 'fire',
  snipclaw: 'water',
  panewhirr: 'wind',
  chainwraith: 'dark',
  bramblebear: 'earth',
  ashtusk: 'fire',
  vespril: 'water',
  fanjack: 'wind',
  gravebloom: 'dark',
  fellstump: 'earth',
  forgehulk: 'fire',
  murkin: 'water',
  skitterel: 'wind',
  cryptshell: 'dark',
  quarryback: 'earth',
  bristlehog: 'fire',
  foamcap: 'water',
  sporeplume: 'wind',
  sorrowstilt: 'dark',
  kabulk: 'earth',
  matchling: 'fire',
  gulpwick: 'water',
  chimbrel: 'wind',
  sicklehood: 'dark',
  quagmaw: 'earth',
  wickmoth: 'fire',
  brammel: 'water',
  lantessa: 'wind',
  hollowstag: 'dark',
  wickerhusk: 'earth',
  emberwren: 'fire',
  conchguard: 'water',
  vaneknight: 'wind',
  voidmaw: 'dark',
  grumblode: 'earth',
  sootcap: 'fire',
  bellbuoy: 'water',
  skreave: 'wind',
  shroudlamp: 'dark',
  chirrgrit: 'earth',
  steamfin: 'fire',
  quintel: 'water',
  curlhart: 'wind',
  gallowplate: 'dark',
  gillstub: 'earth',
  kindletoad: 'fire',
  pondstrider: 'water',
  gyrodillo: 'wind',
  mournbell: 'dark',
  cobbleroll: 'earth',
  flarecrow: 'fire',
  slushmaw: 'water',
  cyclonarch: 'wind',
  hooklure: 'dark',
  flintwren: 'earth',
  hearthmole: 'fire',
  kraulk: 'water',
  vellisk: 'wind',
  quietus: 'dark',
  moldwarp: 'earth',
  scorchbriar: 'fire',
  reefknight: 'water',
  millox: 'wind',
  unblink: 'dark',
  spadeling: 'earth',
  kilnshell: 'fire',
  grumbol: 'water',
  nubilan: 'wind',
  glasshade: 'dark',
  helmdelver: 'earth',
  charspine: 'fire',
  vorrow: 'water',
  dartfinch: 'wind',
  inknuckle: 'dark',
  thornhare: 'earth',
  pyrecairn: 'fire',
  rainheron: 'water',
  glidefin: 'wind',
  veilcap: 'dark',
  cairnlith: 'earth',
  slagram: 'fire',
  clubprawn: 'water',
  whirlseed: 'wind',
  waxwick: 'dark',
  drusehog: 'earth',
  coalscythe: 'fire',
  kelpwarden: 'water',
  velmoth: 'wind',
  nightlynx: 'dark',
  terrakin: 'earth',
  cindercoil: 'fire',
};

/** Draw size per species — hidden: it only drives sprite scale and z-order. */
export const SPECIES_SIZE: Record<SpeciesId, 1 | 2 | 3> = {
  slime: 1,
  bat: 1,
  ghost: 2,
  golem: 3,
  dragon: 3,
  lumibel: 1,
  kitekin: 1,
  rictus: 2,
  lichenwing: 2,
  brimhide: 3,
  sopwit: 1,
  nimbling: 1,
  hexweaver: 2,
  sumpfang: 2,
  anvilclaw: 3,
  snipclaw: 1,
  panewhirr: 2,
  chainwraith: 2,
  bramblebear: 3,
  ashtusk: 3,
  vespril: 1,
  fanjack: 2,
  gravebloom: 2,
  fellstump: 3,
  forgehulk: 3,
  murkin: 1,
  skitterel: 2,
  cryptshell: 2,
  quarryback: 3,
  bristlehog: 1,
  foamcap: 1,
  sporeplume: 2,
  sorrowstilt: 3,
  kabulk: 3,
  matchling: 1,
  gulpwick: 2,
  chimbrel: 2,
  sicklehood: 3,
  quagmaw: 3,
  wickmoth: 1,
  brammel: 2,
  lantessa: 2,
  hollowstag: 3,
  wickerhusk: 3,
  emberwren: 1,
  conchguard: 2,
  vaneknight: 2,
  voidmaw: 3,
  grumblode: 1,
  sootcap: 1,
  bellbuoy: 2,
  skreave: 3,
  shroudlamp: 3,
  chirrgrit: 1,
  steamfin: 1,
  quintel: 2,
  curlhart: 3,
  gallowplate: 3,
  gillstub: 1,
  kindletoad: 1,
  pondstrider: 2,
  gyrodillo: 3,
  mournbell: 3,
  cobbleroll: 1,
  flarecrow: 2,
  slushmaw: 2,
  cyclonarch: 3,
  hooklure: 1,
  flintwren: 1,
  hearthmole: 2,
  kraulk: 3,
  vellisk: 3,
  quietus: 1,
  moldwarp: 1,
  scorchbriar: 2,
  reefknight: 3,
  millox: 3,
  unblink: 1,
  spadeling: 1,
  kilnshell: 2,
  grumbol: 3,
  nubilan: 3,
  glasshade: 1,
  helmdelver: 2,
  charspine: 2,
  vorrow: 3,
  dartfinch: 1,
  inknuckle: 1,
  thornhare: 2,
  pyrecairn: 2,
  rainheron: 3,
  glidefin: 1,
  veilcap: 1,
  cairnlith: 2,
  slagram: 2,
  clubprawn: 3,
  whirlseed: 1,
  waxwick: 1,
  drusehog: 2,
  coalscythe: 3,
  kelpwarden: 3,
  velmoth: 1,
  nightlynx: 2,
  terrakin: 2,
  cindercoil: 3,
};

/**
 * Attack timing per species (hidden attribute, user change 2026-09-06): how
 * many ms into each 1000-ms volley window the swing lands — quick bats strike
 * first, lumbering golems wind up longest. Damage is unchanged (one swing per
 * member per window), only WHEN it lands differs, so a party never fires as
 * one block.
 */
export const SPECIES_ATTACK_DELAY_MS: Record<SpeciesId, number> = {
  slime: 200,
  bat: 0,
  ghost: 400,
  golem: 800,
  dragon: 600,
  lumibel: 200,
  kitekin: 200,
  rictus: 300,
  lichenwing: 450,
  brimhide: 700,
  sopwit: 50,
  nimbling: 250,
  hexweaver: 350,
  sumpfang: 350,
  anvilclaw: 750,
  snipclaw: 150,
  panewhirr: 250,
  chainwraith: 450,
  bramblebear: 600,
  ashtusk: 850,
  vespril: 0,
  fanjack: 300,
  gravebloom: 500,
  fellstump: 850,
  forgehulk: 900,
  murkin: 250,
  skitterel: 350,
  cryptshell: 550,
  quarryback: 750,
  bristlehog: 100,
  foamcap: 250,
  sporeplume: 400,
  sorrowstilt: 550,
  kabulk: 550,
  matchling: 150,
  gulpwick: 450,
  chimbrel: 450,
  sicklehood: 600,
  quagmaw: 650,
  wickmoth: 50,
  brammel: 250,
  lantessa: 500,
  hollowstag: 650,
  wickerhusk: 700,
  emberwren: 0,
  conchguard: 550,
  vaneknight: 550,
  voidmaw: 700,
  grumblode: 100,
  sootcap: 250,
  bellbuoy: 500,
  skreave: 600,
  shroudlamp: 750,
  chirrgrit: 50,
  steamfin: 200,
  quintel: 400,
  curlhart: 650,
  gallowplate: 800,
  gillstub: 150,
  kindletoad: 150,
  pondstrider: 300,
  gyrodillo: 700,
  mournbell: 900,
  cobbleroll: 250,
  flarecrow: 450,
  slushmaw: 550,
  cyclonarch: 750,
  hooklure: 0,
  flintwren: 0,
  hearthmole: 500,
  kraulk: 700,
  vellisk: 800,
  quietus: 50,
  moldwarp: 200,
  scorchbriar: 400,
  reefknight: 850,
  millox: 850,
  unblink: 100,
  spadeling: 250,
  kilnshell: 550,
  grumbol: 750,
  nubilan: 900,
  glasshade: 150,
  helmdelver: 500,
  charspine: 250,
  vorrow: 650,
  dartfinch: 0,
  inknuckle: 200,
  thornhare: 250,
  pyrecairn: 350,
  rainheron: 600,
  glidefin: 50,
  veilcap: 250,
  cairnlith: 300,
  slagram: 300,
  clubprawn: 550,
  whirlseed: 100,
  waxwick: 250,
  drusehog: 550,
  coalscythe: 550,
  kelpwarden: 900,
  velmoth: 150,
  nightlynx: 250,
  terrakin: 400,
  cindercoil: 600,
};

/**
 * Attack delay of any runtime species id; unknown → 0. Never throws.
 *
 * The lookups below go through isSpeciesId rather than `table[id] ?? default`:
 * the tables are object literals, so an id like 'toString' or '__proto__'
 * would otherwise resolve to an inherited property instead of falling back.
 * Species ids reach these functions straight out of save files, IPC and the
 * server roster.
 */
export function attackDelayOf(speciesId: string): number {
  return isSpeciesId(speciesId) ? SPECIES_ATTACK_DELAY_MS[speciesId] : 0;
}

/** Type of any runtime species id; unknown → slime's 'water'. Never throws. */
export function typeOf(speciesId: string): MonsterType {
  return isSpeciesId(speciesId) ? SPECIES_TYPE[speciesId] : 'water';
}

/** Size of any runtime species id; unknown → 1. Never throws. */
export function sizeOf(speciesId: string): 1 | 2 | 3 {
  return isSpeciesId(speciesId) ? SPECIES_SIZE[speciesId] : 1;
}

const SPECIES_DISPLAY_NAMES: Record<SpeciesId, string> = {
  slime: 'Slime',
  bat: 'Bat',
  ghost: 'Ghost',
  golem: 'Golem',
  dragon: 'Dragon',
  lumibel: 'Lumibel',
  kitekin: 'Kitekin',
  rictus: 'Rictus',
  lichenwing: 'Lichenwing',
  brimhide: 'Brimhide',
  sopwit: 'Sopwit',
  nimbling: 'Nimbling',
  hexweaver: 'Hexweaver',
  sumpfang: 'Sumpfang',
  anvilclaw: 'Anvilclaw',
  snipclaw: 'Snipclaw',
  panewhirr: 'Panewhirr',
  chainwraith: 'Chainwraith',
  bramblebear: 'Bramblebear',
  ashtusk: 'Ashtusk',
  vespril: 'Vespril',
  fanjack: 'Fanjack',
  gravebloom: 'Gravebloom',
  fellstump: 'Fellstump',
  forgehulk: 'Forgehulk',
  murkin: 'Murkin',
  skitterel: 'Skitterel',
  cryptshell: 'Cryptshell',
  quarryback: 'Quarryback',
  bristlehog: 'Bristlehog',
  foamcap: 'Foamcap',
  sporeplume: 'Sporeplume',
  sorrowstilt: 'Sorrowstilt',
  kabulk: 'Kabulk',
  matchling: 'Matchling',
  gulpwick: 'Gulpwick',
  chimbrel: 'Chimbrel',
  sicklehood: 'Sicklehood',
  quagmaw: 'Quagmaw',
  wickmoth: 'Wickmoth',
  brammel: 'Brammel',
  lantessa: 'Lantessa',
  hollowstag: 'Hollowstag',
  wickerhusk: 'Wickerhusk',
  emberwren: 'Emberwren',
  conchguard: 'Conchguard',
  vaneknight: 'Vaneknight',
  voidmaw: 'Voidmaw',
  grumblode: 'Grumblode',
  sootcap: 'Sootcap',
  bellbuoy: 'Bellbuoy',
  skreave: 'Skreave',
  shroudlamp: 'Shroudlamp',
  chirrgrit: 'Chirrgrit',
  steamfin: 'Steamfin',
  quintel: 'Quintel',
  curlhart: 'Curlhart',
  gallowplate: 'Gallowplate',
  gillstub: 'Gillstub',
  kindletoad: 'Kindletoad',
  pondstrider: 'Pondstrider',
  gyrodillo: 'Gyrodillo',
  mournbell: 'Mournbell',
  cobbleroll: 'Cobbleroll',
  flarecrow: 'Flarecrow',
  slushmaw: 'Slushmaw',
  cyclonarch: 'Cyclonarch',
  hooklure: 'Hooklure',
  flintwren: 'Flintwren',
  hearthmole: 'Hearthmole',
  kraulk: 'Kraulk',
  vellisk: 'Vellisk',
  quietus: 'Quietus',
  moldwarp: 'Moldwarp',
  scorchbriar: 'Scorchbriar',
  reefknight: 'Reefknight',
  millox: 'Millox',
  unblink: 'Unblink',
  spadeling: 'Spadeling',
  kilnshell: 'Kilnshell',
  grumbol: 'Grumbol',
  nubilan: 'Nubilan',
  glasshade: 'Glasshade',
  helmdelver: 'Helmdelver',
  charspine: 'Charspine',
  vorrow: 'Vorrow',
  dartfinch: 'Dartfinch',
  inknuckle: 'Inknuckle',
  thornhare: 'Thornhare',
  pyrecairn: 'Pyrecairn',
  rainheron: 'Rainheron',
  glidefin: 'Glidefin',
  veilcap: 'Veilcap',
  cairnlith: 'Cairnlith',
  slagram: 'Slagram',
  clubprawn: 'Clubprawn',
  whirlseed: 'Whirlseed',
  waxwick: 'Waxwick',
  drusehog: 'Drusehog',
  coalscythe: 'Coalscythe',
  kelpwarden: 'Kelpwarden',
  velmoth: 'Velmoth',
  nightlynx: 'Nightlynx',
  terrakin: 'Terrakin',
  cindercoil: 'Cindercoil',
};

/** Display name of any runtime species id; unknown → the id itself. */
export function displayNameOf(speciesId: string): string {
  return isSpeciesId(speciesId) ? SPECIES_DISPLAY_NAMES[speciesId] : speciesId;
}

/**
 * Build a monster at a progress index with the selected species. Omitting the
 * species restores the legacy catalog order. Tier increments every
 * SPECIES_IDS.length monsters; maxHp comes from monsterMaxHp(index).
 * Display name is "Slime Lv.3" style, where the Lv number is tier + 1.
 * Every 8th monster is a boss:
 * 5x maxHp and a " BOSS" name suffix.
 */
export function monsterForIndex(index: number, species?: SpeciesId): MonsterDef {
  const i = Math.max(0, Math.floor(index));
  const speciesId = species ?? SPECIES_IDS[i % SPECIES_IDS.length] ?? SPECIES_IDS[0];
  const tier = Math.floor(i / SPECIES_IDS.length);
  const boss = isBoss(i);
  return {
    index: i,
    speciesId,
    name: `${SPECIES_DISPLAY_NAMES[speciesId]} Lv.${tier + 1}${boss ? ' BOSS' : ''}`,
    maxHp: monsterMaxHp(i) * (boss ? BOSS_HP_MULT : 1n),
    tier,
    boss,
    type: SPECIES_TYPE[speciesId],
  };
}
