import assert from 'node:assert/strict';
import console from 'node:console';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root='.agentdoc/v10-20260917T070144Z',dir=root+'/balance-validation-01';
const read=p=>JSON.parse(readFileSync(p,'utf8')),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const protocol=read('docs/v0.10/EVALUATION_PROTOCOL.json'), report=read(dir+'/report.json'),result=report.reports[0];
assert.equal(result.candidate.id,'C');assert(result.passed);assert.deepEqual(report.binding,report.after);
const rows=protocol.policies.flatMap(policy=>readFileSync(dir+'/C-'+policy+'.jsonl','utf8').trim().split('\n').map(JSON.parse));
assert.equal(rows.length,2400);
const quantile=(values,p)=>values.length?[...values].sort((a,b)=>a-b)[Math.floor((values.length-1)*p)]:null;
const distribution=values=>({n:values.length,p10:quantile(values,.1),p50:quantile(values,.5),p90:quantile(values,.9)});
const groups=result.summaries.map(summary=>{
  const group=rows.filter(r=>r.policy===summary.policy&&r.minutes===summary.minutes),templates={};
  for(const r of group)for(const [id,minutes]of Object.entries(r.templateMinutes))templates[id]=(templates[id]??0)+minutes;
  const total=Object.values(templates).reduce((a,b)=>a+b,0),sorted=Object.entries(templates).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
  const ratioRows=group.filter(r=>BigInt(r.spent)>BigInt(r.expansionSpend));
  return {...summary,purchases:distribution(group.map(r=>r.purchases)),purchaseSpend:distribution(group.map(r=>Number(BigInt(r.spent)-BigInt(r.enhanceSpend)-BigInt(r.expansionSpend)))),
    rebirthUnequips:distribution(group.map(r=>r.rebirthUnequips)),eligibleAttempts:distribution(group.map(r=>r.eligibleAttempts)),
    weaponContributionPointsPer1000GrossGearGold:{...distribution(ratioRows.map(r=>1000*r.weaponGainPercent/Number(BigInt(r.spent)-BigInt(r.expansionSpend)))),zeroSpend:group.length-ratioRows.length},
    spendingFractionOfAvailableGold:distribution(group.map(r=>Number(r.spent)/(Number(r.income)+Number(r.sales)+(r.policy==='wealthy-save'?1000000:0)))),
    topWeaponTemplates:sorted.slice(0,5).map(([id,minutes])=>({id,minutes,share:total?minutes/total:0,players:group.filter(r=>(r.templateMinutes[id]??0)>0).length})),
    weaponTemplatesUsed:sorted.length,specificEpicZeroRange:{minimum:Math.min(...Object.values(summary.predictedSpecificEpicZeroRates)),maximum:Math.max(...Object.values(summary.predictedSpecificEpicZeroRates))}};
});
const baselinePath=root+'/baseline/validation-02/report.json',baseline=read(baselinePath);
const derived={version:10,selected:'C',source:{validationReportHash:hash(dir+'/report.json'),baselineReportHash:hash(baselinePath),raw:Object.fromEntries(protocol.policies.map(p=>[p,hash(dir+'/C-'+p+'.jsonl')]))},
  definitions:{weaponContributionPointsPer1000GrossGearGold:'1000 × checkpoint weaponGainPercent / (cumulative spent − expansionSpend); includes purchase and enhancement spending on all gear, dropped gear and rebirth effects; descriptive, not causal purchase ROI. Zero spend is undefined and explicitly counted, not silently removed.',
    topWeaponTemplates:'Top five by pooled equipped weapon minutes; denominator is all equipped weapon minutes within this policy/horizon. Accessory template minutes were not recorded; identical four-copy uptime was recorded.',
    spendingFractionOfAvailableGold:'Cumulative spending / (ordinary gold income + sale proceeds + initial wealthy fixture funds). Median component amounts do not sum to a median identity.'},groups};
writeFileSync(root+'/balance/derived.json',JSON.stringify(derived,null,2)+'\n');
const fmt=(n,d=2)=>n===null?'not reached':n.toLocaleString('en-US',{maximumFractionDigits:d}),pct=n=>fmt(n*100)+'%', med=o=>fmt(o.p50),tail=o=>fmt(o.p50)+' / '+fmt(o.p90);
let md='\n## Held-out evaluation\n\n';
md+='Candidate C passed all four registered selection checks on seeds 50001–50100: 8 policy labels × 100 trajectories × 3 checkpoints = 2,400 rows, with seven distinct behaviors and shared-seed/checkpoint correlations. The production source remained unchanged throughout the run. The independent verifier checks raw denominators, exact currency conservation, compiled candidate/source binding and recomputed summaries.\n\n';
md+='Raw and canonical summaries: `'+dir+'/report.json`. Additional reproducible tables and definitions: `'+root+'/balance/derived.json` (generated by `balance/derive.mjs` in that evidence directory). All arrival quantiles retain nonarrivals as infinity.\n\n';
md+='| Policy | First common purchase at 2h p10 / p50 / p90, minutes | Not purchased by 2h | Current weapon contribution at 2h p50 | Purchases by 2h p50 |\n|---|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>g.minutes===120))md+=`| ${g.policy} | ${fmt(g.firstCommonPurchase.p10)} / ${fmt(g.firstCommonPurchase.p50)} / ${fmt(g.firstCommonPurchase.p90)} | ${g.firstCommonPurchase.nonarrival}/100 | ${fmt(g.weaponGainPercent.p50)}% | ${med(g.purchases)} |\n`;
md+='\n| Policy at 8h | Ordinary income p50 | Wallet p50 | Purchases spent p50 | Enhancement spent p50 | Expansion spent p50 | Share of available gold spent p50 |\n|---|---:|---:|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>g.minutes===480))md+=`| ${g.policy} | ${med(g.income)}G | ${med(g.coins)}G | ${med(g.purchaseSpend)}G | ${med(g.enhanceSpend)}G | ${med(g.expansionSpend)}G | ${pct(g.spendingFractionOfAvailableGold.p50)} |\n`;
md+='\nEach spending category includes destroyed items where applicable. Wealthy-save begins with 1,000,000G excluded from ordinary income but included in available resources. Separate medians are not an accounting identity; the exact identity passes for every raw trajectory.\n\n';
md+='| Policy at 8h | Temporary copies destroyed p50 / p90 | Enhancement failures p50 / p90 | Rebirth unequips p50 | Longest unarmed interval p50 / p90, minutes |\n|---|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>g.minutes===480))md+=`| ${g.policy} | ${tail(g.tempDestroyed)} | ${tail(g.enhanceDestroyed)} | ${med(g.rebirthUnequips)} | ${fmt(g.weaponlessLongestMs.p50/60000)} / ${fmt(g.weaponlessLongestMs.p90/60000)} |\n`;
md+='\nThe unarmed measure includes onboarding; it does not isolate recovery after a failed enhancement. Rebirth unequips count removals from equipped slots, not permanent item losses. Temporary destruction counts include replacement and confirmed hero-change deletion.\n\n';
md+='| Rebirth policy | Horizon | Tier 1 users / median minutes | Tier 2 users / median minutes | Tier 3 users / median minutes | Tier 4 users / median minutes |\n|---|---:|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>['immediate-rebirth','deferred-rebirth'].includes(g.policy)))md+=`| ${g.policy} | ${g.minutes}min | ${g.tierMinutes.map(t=>t.users+'/100 / '+fmt(t.p50)).join(' | ')} |\n`;
md+='\n| Policy at 8h | Top weapon template | Share of equipped weapon time | Same-template four-accessory uptime | Weapon contribution points per 1,000G spent on gear, p50 | Zero-spend cases |\n|---|---|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>g.minutes===480)){const t=g.topWeaponTemplates[0],v=g.weaponContributionPointsPer1000GrossGearGold;md+=`| ${g.policy} | ${t?.id??'none'} | ${pct(t?.share??0)} | ${pct(g.fourCopyRate)} | ${v.p50===null?'undefined':fmt(v.p50,6)} | ${v.zeroSpend}/100 |\n`;}
md+='\nThe final ratio divides current weapon contribution in percentage points by cumulative gross equipment purchase and enhancement spending. It includes dropped equipment and spending on accessories, and is a descriptive opportunity-cost proxy, not causal purchase efficiency. Zero-spend cases have no defined ratio; their count and the remaining ratio denominator are preserved. Accessory template uptime was not separately logged, so the template concentration table covers weapons and the four-copy metric covers accessories.\n\n';
md+='| Policy at 8h | Observed no epic | Predicted no epic | Predicted no particular epic, range over 56 templates | Eligible spawned opportunities p50 |\n|---|---:|---:|---:|---:|\n';
for(const g of groups.filter(g=>g.minutes===480))md+=`| ${g.policy} | ${pct(g.epicZeroRate)} | ${pct(g.predictedEpicZeroRate)} | ${pct(g.specificEpicZeroRange.minimum)}–${pct(g.specificEpicZeroRange.maximum)} | ${med(g.eligibleAttempts)} |\n`;
md+='\nThe complete 56-template probability vectors remain in the canonical report. Predicted values include the last spawned boss even when still alive; observations require a completed kill. The independence formula describes the prescribed opportunities, not a completion guarantee.\n\n';
md+='| Descriptive old/new reference | 0.9.1 wallet p50 | 0.10.0 wallet p50 | 0.10.0 ordinary income p50 |\n|---|---:|---:|---:|\n';
for(const minutes of [30,120,480]){const old=baseline.summary.find(g=>g.policy==='active-10m-visits'&&g.minutes===minutes),g=groups.find(g=>g.policy==='deferred-rebirth'&&g.minutes===minutes);md+=`| Ten-minute visits, ${minutes}min | ${fmt(old.coins.p50)}G | ${med(g.coins)}G | ${med(g.income)}G |\n`;}
md+='\nThis baseline comparison uses different registered seed sets and equipment-enabled actions; it is descriptive rather than paired causal evidence. The old build does not spend on equipment. Gold issuance per kill is unchanged, while gear can change progression and the number of kills.\n\n';
md+='The slowest policy/horizon averaged '+fmt(Math.max(...groups.map(g=>g.processingMsPerVirtualHour)))+'ms of simulation processing per virtual hour, below the registered 10,000ms limit. This is a simulation harness check, not an Electron CPU or memory benchmark; native runtime evidence is separate. Human playtesting was not performed.\n';
writeFileSync(root+'/balance/heldout-report.md',md);
writeFileSync(root+'/balance/final.json',JSON.stringify({version:10,selected:'C',exploration:root+'/balance-explore-04',validation:dir,report:'docs/v0.10/BALANCE_REPORT.md',coreHash:report.binding.coreHash,protocolHash:report.binding.protocolHash,candidateHash:report.binding.candidateHash,rows:2400,policies:8,seedsPerPolicy:100,hardGates:protocol.hardGates},null,2)+'\n');
console.log(JSON.stringify({derived:root+'/balance/derived.json',fragment:root+'/balance/heldout-report.md',final:root+'/balance/final.json'}));
